# Basic information about this project
[content]
name = "modDynamicScabbards"
description = "Match your swords of any quality with your witcher armor."
version = "2.0.1"
authors = ["Fufec"]
game_version = "4.04"
scripts_root = "content/scripts"

# Any dependencies that this project might need
[dependencies]
content0 = true

# For details check the manual
# https://spontancombust.github.io/witcherscript-ide/user-manual/project-system/#manifest-format
