# Basic information about this project
[content]
name = "mod0_DS_WPIAO_Patch"
description = "A patch for Dynamic Scabbards and Wear Preview Items As Outfits."
version = "1.0.0"
authors = ["Fufec"]
game_version = "4.04"
scripts_root = "content/scripts"

# Any dependencies that this project might need
[dependencies]
content0 = true

# For details check the manual
# https://spontancombust.github.io/witcherscript-ide/user-manual/project-system/#manifest-format
